### ISSUE TITLE
Allow changes in Layout

### ISSUE THREAD

**Issue by KristianMariyanov** [BlazorRepl/BlazorRepl#10]
Allow user to define their own layout

**Comment by vladislav-karamfilov** [comment]
We support this since we implemented multiple components support: https://github.com/BlazorRepl/BlazorRepl/issues/2. The steps to achieve this:
- create a custom layout component and marking it with directive `@inherits LayoutComponentBase`
- use the new layout on the pages you want through directive `@layout TestLayout`

Here is an example: https://blazorrepl.com/repl/GPYmFrai50rkzuEs51
