### ISSUE TITLE
Blazor Server? Using of dll libraries?

### ISSUE THREAD

**Issue by AntonitoMt** [BlazorRepl/BlazorRepl#116]
Could it be integrated into a Blazor Server project? 

If so, how could I add (usings) the available libraries of the project (or solution) to make them available to the code to test?

**Comment by KristianMariyanov** [comment]
Hello @AntonitoMt

Can you please elaborate on your question? 
From what I understand, you want to integrate the Blazor REPL app inside a server app. Is that correct?

**Comment by AntonitoMt** [comment]
Exactly, inside a Blazor Server app.  Although, for the moment, just testing.

What I would like is for the compiled code to be able to access the other libraries in the solution.

ps: Excuse me as my english is not very good :)

**Comment by vladislav-karamfilov** [comment]
Hey @AntonitoMt! Blazor REPL cannot be easily used inside a Blazor server app because some of the mechanics of our project are specific to the Web Assembly hosting model of Blazor. Maybe you might be able to load it in a browser-like control in your Blazor server app but that might have many obstacles. The described scenario is not something that we strive to supporting. 

Having that said, you still might use our user code compilation approach that's in `CompilationService`: https://github.com/BlazorRepl/BlazorRepl/blob/7464361135876b3022f07ffb7ff0f4c6a609cb48/Core/CompilationService.cs#L22 As you already found out, you can add the assembly you want users to be able to use in the `basicReferenceAssemblyRoots`: https://github.com/BlazorRepl/BlazorRepl/blob/7464361135876b3022f07ffb7ff0f4c6a609cb48/Core/CompilationService.cs#L106 and you can also add the using statement(s) in the `DefaultImports`: https://github.com/BlazorRepl/BlazorRepl/blob/7464361135876b3022f07ffb7ff0f4c6a609cb48/Core/CompilationService.cs#L88 This part of the app can be easily reused but other parts like storing the compiled assembly in the browser and executing it entirely in the browser are not possible in a Blazor server app. An idea that we are not sure can work but comes to our mind is to research building a composite of a Blazor server app inside of which you have a Blazor Web Assembly app.

**Comment by AntonitoMt** [comment]
Understood. 

Thanks for your excellent explanation.   And also thank you for your effort in developing that great tool.  I wish you a lot of success!
