### ISSUE TITLE
Thank you for BlazorREPL

### ISSUE THREAD

**Issue by henon** [BlazorRepl/BlazorRepl#70]
Hi guys,

we used BlazorREPL for people to be able to try out our new open source Material Design Blazor component library [MudBlazor](https://mudblazor.com). For that we adapted BlazorREPL to load the MudBlazor nuget and also refurbished the GUI using our library components. The result is https://try.mudblazor.com/

Since you guys really did all the hard work to make this possible, we prominently display a link to BlazorREPL and give you all the credit you deserve of course.  

So thank you and best wishes from the MudBlazor project.

**Comment by vladislav-karamfilov** [comment]
Hey, @henon! We are really happy to know that you find Blazor REPL useful and have used it in the TryMudBlazor web app. The component library looks very cool. Allowing users to try it out directly in the browser is a concrete implementation of our vision for the Blazor REPL project. Thank you for mentioning our project in your web app!

We have noticed that you are using the staging version of Blazor REPL's snippets API. We want you to be aware that this API is not reliable and we clean up the generated data on a regular basis. We have planned to make it private and in addition to it, to provide a very simple implementation in the near future. Since you, guys, are now using it and we want to support you in your endeavor, we are committed to keep it public and not delete any data until the end of the year. We hope that this is enough time for you to make your own version of the snippets API and we are even ready to advice you through the process. If you have any questions, please write us back.

Good luck with your project!

**Comment by vladislav-karamfilov** [comment]
Closing this as we sorted things out with the MudBlazor team.
